version: '3'
services:
  db:
    image: postgres
    container_name: virtual-secretary-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: virtual-secretary-db
      PGDATA: /data/postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data/pg:/data/postgres

    ports:
      - '5432:5432'
