services:
  db:
    image: postgres
    container_name: virtual-secretary-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: virtual-secretary-db
      PGDATA: /data/postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data/pg:/data/postgres
    ports:
      - '5432:5432'

  redis:
    image: redis:alpine
    container_name: evolution_redis
    ports:
      - '6379:6379'

  evolution-api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:v2.3.7
    restart: always
    ports:
      - '8080:8080'
    env_file:
      - .env.evolution
    environment:
      - DATABASE_ENABLED=true
      - DATABASE_CONNECTION_URI=postgres://postgres:docker@virtual-secretary-db:5432/evolution_api?sslmode=disable
      - DATABASE_SAVE_DATA_INSTANCE=true
    volumes:
      - evolution_store:/evolution/store
      - evolution_instances:/evolution/instances
    depends_on:
      - db
      - redis
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  evolution_store:
  evolution_instances:

networks:
  evolution_network:
    driver: bridge
